[dev]
  # The command to run to publish
  command = "yarn start"
  port = 8888
  targetPort = 3000

  # The files to publish will output here
  publish = "dist"

  functions = "functions"

[build]
  # Only run builds on changes to the packages/vite-app-ts directory
#  ignore = "./netlify_ignore.sh"

  # The command to run to publish
  command = "yarn cypress run --component --record && yarn build"

  # The files to publish will output here
  publish = "dist"

  functions = "functions"
[build.environment]
  CI = "false"
  YARN_VERSION = "3.2.1"
  YARN_CACHE_FOLDER = "/opt/buildhome/.yarn_cache"
  NODE_VERSION = "16.16.0"

[context."release/*"]
  command = "yarn build:staging"
[context."release/*".environment]
  CI = "true"

[context.production]
  command = "yarn build:prod"
[context.production.environment]
  CI = "true"

[[plugins]]
  package = "/plugins/builder"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200