import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import TwitterLoanTerms from "../components/TwitterLoanTerms";
import { useMoralis } from "react-moralis";




const supportedChains = ["137", "5"];

export default function Home() {
  const { isWeb3Enabled, chainId } = useMoralis();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {
        isWeb3Enabled ? (
          <div>
            {supportedChains.includes(parseInt(chainId).toString()) ? (

              <p>
                <div className="flex flex-row">
                  <TwitterLoanTerms className="p-8" />
                  {/* <button onClick={async () => {
                    await getTwitterHandle()
                  }}>Click Now</button> */}
                </div>
              </p>
            ) : (
              <div>{`Please switch to a supported chainId. The supported Chain Ids are: ${supportedChains}`}</div>
            )}
          </div>
        ) : (
          <div>Please connect to a Wallet</div>
        )}
    </div>)


}
